# Generated by Django 4.2.7 on 2023-11-27 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='users',
            field=models.ManyToManyField(related_name='objects', to=settings.AUTH_USER_MODEL, verbose_name='Товары пользователей'),
        ),
    ]
